-- İzorder içeriği için veritabanı şeması oluşturma
-- Tarihçe içeriği için tablo
CREATE TABLE history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- İletişim bilgileri için tablo
CREATE TABLE contact (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  address TEXT NOT NULL,
  phone TEXT NOT NULL,
  email TEXT NOT NULL,
  social_media JSONB DEFAULT '{}',
  map_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Yönetici kullanıcıları için rol
CREATE TABLE admin_users (
  id UUID REFERENCES auth.users NOT NULL PRIMARY KEY,
  email TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'admin',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Row Level Security (RLS) politikaları

-- Tarihçe tablosu için RLS
ALTER TABLE history ENABLE ROW LEVEL SECURITY;

-- Herkes tarihçe verilerini okuyabilir
CREATE POLICY "Herkes tarihçe içeriğini okuyabilir" ON history
  FOR SELECT
  USING (true);

-- Sadece admin kullanıcılar tarihçe verilerini düzenleyebilir
CREATE POLICY "Sadece admin kullanıcılar tarihçe verilerini düzenleyebilir" ON history
  FOR ALL
  USING (
    auth.uid() IN (SELECT id FROM admin_users WHERE role = 'admin')
  );

-- İletişim tablosu için RLS
ALTER TABLE contact ENABLE ROW LEVEL SECURITY;

-- Herkes iletişim verilerini okuyabilir
CREATE POLICY "Herkes iletişim bilgilerini okuyabilir" ON contact
  FOR SELECT
  USING (true);

-- Sadece admin kullanıcılar iletişim verilerini düzenleyebilir
CREATE POLICY "Sadece admin kullanıcılar iletişim verilerini düzenleyebilir" ON contact
  FOR ALL
  USING (
    auth.uid() IN (SELECT id FROM admin_users WHERE role = 'admin')
  );

-- Varsayılan veriler ekleme
INSERT INTO history (title, content)
VALUES (
  'İzmir Ordu İli ve İlçeleri Kültür Dayanışma ve Yardımlaşma Derneği',
  'Derneğimiz, Ordulu hemşehrilerimizi bir araya getirmek, kültürel değerlerimizi yaşatmak ve dayanışma içinde olmak amacıyla kurulmuştur. Kuruluşumuzdan bu yana...'
);

INSERT INTO contact (address, phone, email, social_media, map_url)
VALUES (
  'İzmir, Türkiye',
  '+90 232 123 45 67',
  'info@izorder.org',
  '{"facebook": "izorderofficial", "instagram": "izorder"}',
  'https://maps.google.com/maps?q=izmir'
); 